mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('polls.urls', namespace="polls")),
]

polls/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name = "index"),
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name = "detail"),
    url(r'^(?P<question_id>[0-9]+)/vote$', views.vote, name = "vote"),

]

polls/models.py
from django.db import models

# Create your models here.
class Question (models.Model):
    question_text = models.CharField(max_length = 140)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

class Choice (models.Model):
    answer_text = models.CharField(max_length = 20)
    votes = models.IntegerField(default = 0)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __str__(self):
        return self.answer_text

class Choice2 (models.Model):
    answer_text = models.CharField(max_length = 20)
    votes = models.IntegerField(default = 0)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __str__(self):
        return self.answer_text

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
import random

from .models import Question

# Create your views here.

def index(request):

    #dopisac losowanie pierwszego pytania
    latest_question = Question.objects.order_by('-pub_date')
    number = random.choice(latest_question).pk



    request.session['counter']=1
    request.session.modified = True

    context = { 'latest_question' : latest_question }

    return render(request, 'polls/index.html', {'context':context, 'number':number })


def detail(request, question_id):

    question = Question.objects.get(pk=question_id)
    counter = request.session.get('counter', 1)
    request.session.modified = True
    counter_bar = (counter/30)*100

    return render(request, 'polls/detail.html', {'question': question, 'counter_bar':counter_bar, 'counter':counter})


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    return render(request, 'polls/vote.html', {'question': question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk = question_id)

    counter = request.session['counter']
    counter_bar = (counter / 30) * 100

    try:
        selected_choice = question.choice_set.get(pk = request.POST['choice'])
        selected_choice2 = question.choice2_set.get(pk = request.POST['choice2'])
    except:
        return render(request, 'polls/detail.html', {'question': question, 'error_message' : "BRAK ODPOWIEDZI, PROSZĘ WYBRAĆ JEDNĄ Z OPCJI", 'counter_bar':counter_bar, 'counter':counter})
    else:
        selected_choice.votes +=1;
        selected_choice.save()

        selected_choice2.votes += 1;
        selected_choice2.save()

        if counter < 30:
            counter += 1
            request.session['counter'] = counter
            request.session.modified = True
        else:
            counter = 1
            request.session['counter'] = counter
            request.session.modified = True
            return HttpResponseRedirect(reverse('polls:index', args=()))

        #question = Question.objects.get(pk=(int(question_id)+1)) #TUTAJ LOSOWAC NASTĘPNE PYTANIE
        latest_question = Question.objects.order_by('-pub_date')
        question = random.choice(latest_question)


        return HttpResponseRedirect(reverse('polls:detail', args=(question.id,)))

polls/templates/polls/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Określanie sentymentów w wiadomościach z Twittera w języku polskim</title>
    <meta name="description" content="Określanie sentymentów w wiadomościach z Twittera w języku polskim">
    <meta name="keywords" content="Określanie sentymentów w wiadomościach z Twittera w języku polskim, Sentiment analysis, twitter, data-mining, big data">

    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans|Candal|Alegreya+Sans"/>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/css/font-awesome.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/css/imagehover.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/css/style.css' %}"/>
    <!-- =======================================================
        Theme Name: Mentor
        Theme URL: https://bootstrapmade.com/mentor-free-education-bootstrap-theme/
        Author: BootstrapMade.com
        Author URL: https://bootstrapmade.com
    ======================================================= -->
  </head>
  <body>
    <!--Navigation bar-->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'polls:index' %}">Sentiment<span>analysis</span></a>

        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav navbar-right">
          <!--/ <li><a href="#feature">Features</a></li>-->
        </ul>
        </div>
      </div>
    </nav>
    <!--/ Navigation bar-->

    <!--Banner-->
    <div class="banner">
      <div class="bg-color">
        <div class="container">
          <div class="row">
            <div class="banner-text text-center">
              <div class="text-border">
                <h2 class="text-dec">Określanie sentymentów w wiadomościach z Twittera w języku polskim</h2>
              </div>
              <div class="intro-para text-center quote">
                <p class="big-text">Praca dyplomowa: inż. Maciej Bortnowski</p>
				<p class="big-text">Opiekun pracy: dr inż. Joanna Kołodziejczyk</p>
                <p class="small-text">Analiza metod do określania sentymentów w tekstach z Twittera.<br>Wybór adekwatnej metody i implementacja algorytmu do klasyfikacji sentymentów <br>wyrażanych w wiadomościach internautów.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!--/ Banner-->

    <!--Contact-->
    <section id ="vote" class="section-padding">
      <div class="container">
        <div class="row">
          <div class="header-section text-center">

              {% block main_content %}

              {% endblock %}

          </div>

        </div>
      </div>
    </section>
    <!--/ Contact-->
    <!--Footer-->
    <footer id="footer" class="footer">
      <div class="container text-center">
		inż. Maciej Bortnowski <br>
		2017<br>
		______________________________________________________<br>
        ©2016 Mentor Theme. All rights reserved
        <div class="credits">
            <!--
                All the links in the footer should remain intact.
                You can delete the links only if you purchased the pro version.
                Licensing information: https://bootstrapmade.com/license/
                Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=Mentor
            -->
            Designed by <a href="https://bootstrapmade.com/">Free Bootstrap Themes</a>
        </div>
      </div>
    </footer>
    <!--/ Footer-->

    <script src="{% static 'polls/js/jquery.min.js' %}"></script>
    <script src="{% static 'polls/js/jquery.easing.min.js' %}"></script>
    <script src="{% static 'polls/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'polls/js/custom.js' %}"></script>


  </body>
</html>

polls/templates/polls/detail.html
{% extends 'polls/base.html' %}
{% block main_content %}

			<div class="container">

			  <h2>Badanie sentymentów</h2>
			  <!--/ PROGRESS-->
			<div class="progress">
				<div class="progress-bar progress-bar-success progress-bar-striped active" role="progressbar" aria-valuenow="100"
					aria-valuemin="0" aria-valuemax="100" style="width:{{ counter_bar }}%">
					{{ counter }}/30
				</div>
			</div>
			  
			  <!--/ TUTAJ TREŚĆ WPISU!!!!-->
			  <div class="well"> {{ question.question_text}} </div>
			  <br>
			  <p>Prosze wybrać odpowiednią opcję:</p>
			  <br>

               	{% if error_message %}
					<div class="alert alert-danger" role="alert">
						{{ error_message }}
					</div>
				{% endif %}


			  <form class="form-horizontal" role="form" action="{% url 'polls:vote' question.id %}" method="post">

                  {% csrf_token %}

				<div class="form-group">
				
					<label class="col-sm-4 control-label">Sentymenty:</label>
					<div class="col-sm-8">

                        {% for choice in question.choice_set.all %}

						<label class="radio-inline"> <input type="radio" name="choice" id="choice{{forloop.counter}} "
															value="{{choice.id}}"> {{ choice.answer_text }}  </label>
						{% endfor %}

					</div>
				</div>

				  <div class="form-group">

					<label for="choice2" class="col-sm-4 control-label">Które słowo najbardziej wpłynęło na ocenę?</label>
					<div class="col-sm-8">
					<select class="form-control" id="choice2" name="choice2">

						{% for choice2 in question.choice2_set.all %}
						<option name="choice2" id="choice2{{forloop.counter}} " value="{{choice2.id}}">{{ choice2 }}</option>
						{% endfor %}

					</select>
					</div>

				  </div>
				
				<br><br>
				<button type="submit" class="btn btn-success">Następny wpis</button>
			  </form>

			</div>

{% endblock %}

polls/templates/polls/index.html
{% extends 'polls/base.html' %}
{% block main_content %}

<!--/ hrefa losować po przejsciu do kolejnego pytania -->

		  <a href="{{number}}" class="btn btn-submit">ANKIETA</a>

            <h2>O co chodzi?</h2>

            <p>Aby program komputerowy mógł rozpoznawać sentymenty w danej wiadomości należy go tego nauczyć.
Potrzebna jest do tego jak największa ilość danych uczących,
w tym przypadku jest to nic innego jak wpisy z nadanymi przez Ciebie - eksperta etykietami dotyczącymi sentymentów zawartych w wiadomościach. </p>

{% endblock %}

polls/templates/polls/vote.html
{% extends 'polls/base.html' %}
{% block main_content %}

			<div class="container">

			  <h2>Badanie sentymentów</h2>
			  <!--/ PROGRESS-->
			<div class="progress">
				<div class="progress-bar" role="progressbar" aria-valuenow="70"
					aria-valuemin="0" aria-valuemax="100" style="width:70%">
					70%
				</div>
			</div>
			  
			  <!--/ TUTAJ TREŚĆ WPISU!!!!-->
			  <div class="well"> {{ question.question_text}} </div>

                <ul>
                    {% for choice in question.choice_set.all %}
                    <li>{{choice.answer_text}} - {{choice.votes}} vote{{choice.votes|pluralize}}</li>
                    {% endfor %}
                </ul>

                <a href = "{% url 'polls:detail' question_id }%"> GŁOSUJ DALEJ </a>

			</div>

{% endblock %}